[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
monitor_speed = 115200
monitor_dtr = 1
monitor_filters = direct
build_flags =
	-DENABLE_USB_HID=1
	-DENABLE_BASE_EPD=1
	-I../shared
lib_deps =
	adafruit/Adafruit NeoPixel @ ^1.12.3
	zinggjm/GxEPD2 @ ^1.6.2
	adafruit/Adafruit GFX Library @ ^1.11.11
; HID+CDC composite — serial was blank with HID off on this host
