#!/usr/bin/env bash
# Build base + rim and pack a one-button GUI update zip.
# Usage: scripts/pack-firmware.sh [release-tag]
# Output: dist/ffb-firmware-<tag>.zip
#
# Writes shared/ffb_build_stamp.h so MCU firmware strings match the manifest.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TAG="${1:-$(date -u +%Y%m%d)}"
BUILD_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
FW_ID="${TAG} ${BUILD_UTC}"
STAGE="$ROOT/dist/pack-staging"
OUT_DIR="$ROOT/dist"
ZIP="$OUT_DIR/ffb-firmware-${TAG}.zip"
STAMP="$ROOT/shared/ffb_build_stamp.h"

BASE_UF2="$ROOT/firmware-base/.pio/build/pico/firmware.uf2"
RIM_BIN="$ROOT/firmware-rim/.pio/build/pico/firmware.bin"

# Escape for C string literal
c_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

TAG_C=$(c_escape "$TAG")
UTC_C=$(c_escape "$BUILD_UTC")

cat > "$STAMP" <<EOF
#pragma once
// Generated by scripts/pack-firmware.sh — do not edit by hand.
#define FFB_RELEASE_TAG "${TAG_C}"
#define FFB_BUILD_UTC "${UTC_C}"
EOF

echo "==> Stamp: release=${TAG} build_utc=${BUILD_UTC}"
echo "==> Building firmware-base"
pio run -d "$ROOT/firmware-base"

echo "==> Building firmware-rim"
pio run -d "$ROOT/firmware-rim"

test -f "$BASE_UF2" || { echo "missing $BASE_UF2"; exit 1; }
test -f "$RIM_BIN" || { echo "missing $RIM_BIN"; exit 1; }

rm -rf "$STAGE"
mkdir -p "$STAGE" "$OUT_DIR"
cp "$BASE_UF2" "$STAGE/base.uf2"
cp "$RIM_BIN" "$STAGE/rim.bin"

BASE_SHA=$(sha256sum "$STAGE/base.uf2" | awk '{print $1}')
RIM_SHA=$(sha256sum "$STAGE/rim.bin" | awk '{print $1}')
BASE_SIZE=$(wc -c < "$STAGE/base.uf2" | tr -d ' ')
RIM_SIZE=$(wc -c < "$STAGE/rim.bin" | tr -d ' ')

cat > "$STAGE/manifest.json" <<EOF
{
  "format": "ffb-fw-pack",
  "version": 1,
  "product": "rp2040-ffb",
  "release": "${TAG}",
  "build_utc": "${BUILD_UTC}",
  "fw_id": "${FW_ID}",
  "created": "${BUILD_UTC}",
  "base": {
    "file": "base.uf2",
    "sha256": "${BASE_SHA}",
    "size": ${BASE_SIZE},
    "fw_id": "${FW_ID}"
  },
  "rim": {
    "file": "rim.bin",
    "sha256": "${RIM_SHA}",
    "size": ${RIM_SIZE},
    "fw_id": "${FW_ID}"
  },
  "notes": "GUI: flash rim via OTA, then reboot base to BOOTSEL and copy base.uf2. Compare dump base_fw/rim_fw to fw_id."
}
EOF

rm -f "$ZIP"
(
  cd "$STAGE"
  zip -9 -q "$ZIP" manifest.json base.uf2 rim.bin
)

echo "==> Packed $ZIP"
echo "    fw_id=${FW_ID}"
unzip -l "$ZIP"
echo "Done. In ffb-config: Firmware update → pick this zip → Update both."
