[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
monitor_speed = 115200
monitor_dtr = 1
monitor_filters = direct
build_flags =
	-I../shared
lib_deps =
	adafruit/Adafruit NeoPixel @ ^1.12.3
